# Generated by Django 5.1.4 on 2025-02-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default='Valencia_Spain', help_text='Current location of the device', on_delete=django.db.models.deletion.CASCADE, to='rent_tool_app.location'),
        ),
    ]
