# Generated by Django 5.1.4 on 2025-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_tool_app', '0002_alter_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
