# Generated by Django 5.1.4 on 2025-02-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_tool_app', '0003_device_device_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
    ]
