# Generated by Django 5.1.4 on 2025-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_tool_app', '0004_alter_device_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(default='Unknown', help_text='Manufacturer of the device', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.CharField(default='Unknown', help_text='Model number of the device', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Date when the device warranty expires', null=True),
        ),
    ]
